version: 0.2

env:
  variables:
    VITE_REACT_APP_ENV: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing NPM dependencies
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      # Copy the contents of ./build to S3
      - aws s3 cp --recursive ./build s3://moustache-dev-fe/
      
      # Set the cache-control headers for index.html to prevent browser caching
      - >  
        aws s3 cp
        --cache-control="max-age=0, no-cache, no-store, must-revalidate"
        ./build/index.html s3://moustache-dev-fe/
      
      # Invalidate CloudFront cache for index.html and service-worker.js
      - >
        aws cloudfront create-invalidation --distribution-id EGPBWXB2DSI96
        --paths /index.html /service-worker.js

artifacts:
  files:
    - "**/*"
  base-directory: build
